### ISSUE TITLE
Support for user-defined controlled values

### ISSUE THREAD

**Issue by jasloe** [jasloe/archivesspace-drupal#12]
But how? 

e.g.
Level of description
Date label
Extent type

**Comment by seth-shaw-unlv** [comment]
For the custom fields you create fieldSettingsForms. For example, to allow user customization of the Extent types I [overwrote the fieldSettingsForm function](https://github.com/jasloe/archivesspace-drupal/blob/master/src/Plugin/Field/FieldType/ASExtent.php#L138-L158). This allows users to change the default list of extent types.

For example, in the follow screen shot I'm at the field settings form for the archival resource extent field, at the bottom I'm adding the "test|Test" option to Extent Types (which wasn't in the default list).

![adding "test|Test" as an extent type](https://user-images.githubusercontent.com/29869988/40556547-ee11154a-6001-11e8-8708-d8590b2ac7f2.png)

Saving this will allow me to create a resource and see "Test" as an option for extent type.

!["Test" is now an extent type option](https://user-images.githubusercontent.com/29869988/40556518-ce2593c8-6001-11e8-807a-439df8334c5b.png)

I've done this with [the date label and other date sub-fields](https://github.com/jasloe/archivesspace-drupal/blob/master/src/Plugin/Field/FieldType/ASDate.php#L156-L215) too.

**Comment by seth-shaw-unlv** [comment]
Of course, this could also be modified by updating the field's configuration before enabling the module.

E.g. update [field.field.node.archival_resource.field_as_extent.yml settings](https://github.com/jasloe/archivesspace-drupal/blob/master/config/install/field.field.node.archival_resource.field_as_extent.yml#L26) to be:

```
settings:
  extent_types:
    linear_feet: 'Linear Feet'
    files: Files
    gigabytes: Gigabytes
    leaves: Leaves
    megabytes: Megabytes
    photographic_prints: 'Photographic Prints'
    photographic_slides: 'Photographic Slides'
    volumes: Volumes
    test: Test
```
