### ISSUE TITLE
ArchivesSpace Authentication for Migration

### ISSUE THREAD

**Issue by seth-shaw-unlv** [jasloe/archivesspace-drupal#25]
This issue is to track enabling Drupal Migrations to authenticate against ArchivesSpace.

**Comment by seth-shaw-unlv** [comment]
@jasloe

I have a form that allows users to set their API base uri, username, and password. I currently have that all saved to the Drupal State API. I used State because these values wouldn't normally move from dev to prod. We could use the Configuration API instead, if you would prefer.

Also, I included the ability for a migration configuration to override the State values (not that I can think of a case where you would want to).

**Comment by seth-shaw-unlv** [comment]
On further thought, maybe we should include default values in the migrate configs and have Drupal state override those, if set...

E.g. 
```
source:
  plugin: archivesspace
  authentication:
    plugin: archivesspace
    # Can be overwritten by using the form at /admin/structure/archivesspace/settings
    username: 'admin'
    password: 'admin' # I *really* hope you changed this...
    base_uri: 'http://localhost:8089' # Only applies to authentication...
  data_fetcher_plugin: http
  base_uri: 'http://localhost:8089' # Only applies to the listed urls
  urls: /repositories # Can ommitt the server & port (/repositories) if base_uri is set
```

These could then be overwritten by either manually changing it in the config or setting the Drupal state (either `drush sset key value` or the provided form).

Thoughts?
